version: '3'

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    expose:
      - 40000
    ports:
      - "40000:3306"
    volumes:
      - mariadb:/val/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    expose:
      - 40001
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db: